#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prodDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect