#spring:
#  datasource:
#    url: jdbc:h2:mem:testDB
#    driverClassName: org.h2.Driver
#    username:
#    password:
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
#        format_sql: true
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true

spring:
  datasource:
    username: admin
    password: admin123
    url: mysql:jdbc://localhost:127.0.0.1:3306/collateDB/useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

